name: Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "Tools/requirements.txt"
      - name: Install dependencies
        run: pip install -r Tools/requirements.txt
      - name: Build
        run: |
          python Tools/build.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: LufsX/ruleset.isteed.cc
          publish_branch: main
          publish_dir: ./Public
          full_commit_message: GitHub Actions Auto Update
          disable_nojekyll: true
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
