name: Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shell
        run: |
          pip3 install requests
          python3 Tools/build.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: LufsX/ruleset.isteed.cc
          publish_branch: main
          publish_dir: ./Public
          full_commit_message: GitHub Actions Auto Update
          disable_nojekyll: true
          force_orphan: true
